# Generated by Django 4.0.4 on 2022-07-24 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('active', models.BooleanField(default=True, verbose_name='Attiva (Si,No)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='public/assets/images/c', verbose_name='Immagine categoria')),
                ('slug', models.SlugField(editable=False, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorie',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='Attivo (Si/No)')),
                ('ingredients', models.TextField(verbose_name='Ingredienti')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Prezzo')),
                ('default_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods', to='catalogo.category', verbose_name='Categoria di default')),
            ],
            options={
                'verbose_name': 'cibo',
                'verbose_name_plural': 'cibi',
            },
        ),
    ]
