# Generated by Django 4.0.4 on 2022-05-11 11:40

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('active', models.BooleanField(default=True, verbose_name='Attiva (Si,No)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='public/assets/images/m', verbose_name='Logo')),
                ('imageUrl', models.URLField(blank=True, null=True, verbose_name='URL Logo scaricabile')),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marche',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('active', models.BooleanField(default=True, verbose_name='Attiva (Si,No)')),
                ('level', models.IntegerField(default=1, editable=False, verbose_name='Livello')),
                ('image', models.ImageField(blank=True, null=True, upload_to='public/assets/images/c', verbose_name='Immagine categoria')),
                ('slug', models.SlugField(editable=False, verbose_name='Slug')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='commerce.category', verbose_name='Categoria padre')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorie',
            },
        ),
    ]
