# Generated by Django 4.0.4 on 2022-05-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('active', models.BooleanField(verbose_name='Attiva (Si,No)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='public/assets/images/m')),
                ('imageUrl', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'marca',
                'verbose_name_plural': 'marche',
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='imageUrl',
        ),
        migrations.AlterField(
            model_name='category',
            name='active',
            field=models.BooleanField(verbose_name='Attiva (Si,No)'),
        ),
    ]
