# Generated by Django 4.0.4 on 2022-05-27 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='Attivo (Si/No)')),
                ('descrizione_breve', models.TextField(blank=True, max_length=400, null=True, verbose_name='Descrizione breve (400 caratteri)')),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Descrizione')),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='commerce.category', verbose_name='Categorie')),
                ('default_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.category', verbose_name='Categoria di default')),
            ],
        ),
    ]
