# Generated by Django 4.0.4 on 2022-06-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2, verbose_name='Prezzo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='ingredients',
            field=models.TextField(blank=True, null=True, verbose_name='Ingredienti'),
        ),
    ]
