# Generated by Django 4.0.4 on 2022-05-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_manufacturer_remove_category_imageurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Attiva (Si,No)'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Attiva (Si,No)'),
        ),
    ]
