# Generated by Django 4.0.4 on 2022-06-24 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commerce', '0003_alter_food_default_category_alter_food_ingredients_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descrizione stato')),
            ],
            options={
                'verbose_name': 'stato ordine',
                'verbose_name_plural': 'stati ordine',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subTotal', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Totale')),
                ('shippingCosts', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Costi di consegna')),
                ('shippingAddress', models.TextField(blank=True, null=True, verbose_name='Indirizzo di consegna')),
                ('shippingDeliveryTime', models.TextField(blank=True, null=True, verbose_name='Orario di consegna')),
                ('shippingRequired', models.BooleanField(default=False, verbose_name='Consegna a domicilio')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note ordine')),
                ('Cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('orderStatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.orderstatus')),
            ],
            options={
                'verbose_name': 'ordine',
                'verbose_name_plural': 'ordini',
            },
        ),
    ]
