# Generated by Django 4.0.4 on 2022-06-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_orderstatus_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Descrizione stato'),
        ),
    ]
