# Generated by Django 4.0.4 on 2022-06-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payed',
            field=models.BooleanField(default=False, verbose_name='Pagato'),
        ),
    ]
