# Generated by Django 4.0.4 on 2022-07-11 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_order_payed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'verbose_name': 'dettaglio ordine', 'verbose_name_plural': 'dettagli ordini'},
        ),
    ]
