# Generated by Django 4.0.4 on 2022-05-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impostazioni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalimodel',
            name='site_description',
            field=models.TextField(blank=True, default='', verbose_name='Descrizione del sito (verrà usata nel tag Description sulla home'),
        ),
    ]
