# Generated by Django 4.0.4 on 2022-07-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impostazioni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpostazioniGenerali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Site Name', max_length=255, verbose_name='Nome del Sito')),
            ],
            options={
                'verbose_name': 'impostazioni generali',
            },
        ),
        migrations.CreateModel(
            name='ImpostazioniSpedizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_costs', models.DecimalField(blank=True, decimal_places=2, default=2.0, max_digits=4, verbose_name='Spese di consegna')),
            ],
            options={
                'verbose_name': 'Spedizione e consegna',
            },
        ),
        migrations.DeleteModel(
            name='GeneraliModel',
        ),
    ]
