# Generated by Django 4.0.4 on 2022-07-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impostazioni', '0002_impostazionigenerali_impostazionispedizione_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Codice di attivazione'),
        ),
    ]
