# Generated by Django 4.0.4 on 2022-05-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impostazioni', '0002_generalimodel_site_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalimodel',
            name='site_keywords',
            field=models.TextField(blank=True, default='', verbose_name='Parole chiave del sito (verranno usate nel tag Keywords sulla home'),
        ),
    ]
