# Generated by Django 4.0.4 on 2022-07-11 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impostazioni', '0003_generalimodel_site_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalimodel',
            name='maintenance_mode',
        ),
        migrations.RemoveField(
            model_name='generalimodel',
            name='site_description',
        ),
        migrations.RemoveField(
            model_name='generalimodel',
            name='site_keywords',
        ),
    ]
