# Generated by Django 4.0.4 on 2022-07-22 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendite', '0008_alter_orderstatus_badge_css_class'),
        ('impostazioni', '0003_user_activation_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpostazioniOrdini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_created_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_created_state_reverse', to='vendite.orderstatus', verbose_name='Stato per ordine creato')),
                ('default_paid_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_paid_state_reverse', to='vendite.orderstatus', verbose_name='Stato per ordine pagato')),
            ],
            options={
                'verbose_name': 'Ordini',
            },
        ),
    ]
