# Generated by Django 4.0.4 on 2022-05-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icecat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecatcategory',
            name='parent_icecat_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
