# Generated by Django 4.0.4 on 2022-05-11 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
        ('icecat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icecatcategory',
            options={'verbose_name': 'categoria Icecat', 'verbose_name_plural': 'categorie Icecat'},
        ),
        migrations.CreateModel(
            name='IcecatManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icecat_id', models.IntegerField()),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('shop_manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marche_icecat', to='commerce.manufacturer')),
            ],
            options={
                'verbose_name': 'marca Icecat',
                'verbose_name_plural': 'marche Icecat',
            },
        ),
    ]
