# Generated by Django 4.0.4 on 2022-05-11 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icecat', '0002_alter_icecatcategory_options_icecatmanufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icecatmanufacturer',
            name='level',
        ),
        migrations.RemoveField(
            model_name='icecatmanufacturer',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='icecatmanufacturer',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='icecatmanufacturer',
            name='tree_id',
        ),
    ]
