# Generated by Django 4.0.4 on 2022-05-23 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
        ('icecat', '0002_icecatcategory_parent_icecat_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IcecatCategory',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='IcecatManufacturer',
            new_name='Manufacturer',
        ),
    ]
