# Generated by Django 4.0.4 on 2022-05-27 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icecat', '0003_rename_icecatcategory_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'categoria', 'verbose_name_plural': 'categorie'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'marca', 'verbose_name_plural': 'marche'},
        ),
    ]
