# Generated by Django 4.0.4 on 2022-05-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icecat', '0003_remove_icecatmanufacturer_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecatmanufacturer',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
