# Generated by Django 4.0.4 on 2022-05-15 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
        ('icecat', '0004_icecatmanufacturer_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecatmanufacturer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='icecatmanufacturer',
            name='shop_manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marche_icecat', to='commerce.manufacturer', verbose_name='Corrispondenza marca Negozio'),
        ),
    ]
