# Generated by Django 4.0.4 on 2022-07-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activationCode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='emailVerified',
            field=models.BooleanField(default=False, verbose_name='Email verificata'),
        ),
    ]
