# Generated by Django 4.0.4 on 2022-07-11 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilo', '0002_user_activationcode_user_emailverified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='activationCode',
            new_name='activation_code',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='emailVerified',
            new_name='email_verified',
        ),
    ]
