# Generated by Django 4.0.4 on 2022-07-11 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilo', '0003_rename_activationcode_user_activation_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activation_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
    ]
