# Generated by Django 4.0.4 on 2022-07-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilo', '0004_remove_user_activation_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(blank=True, default=False, verbose_name='Email verificata'),
        ),
    ]
