# Generated by Django 4.0.4 on 2022-07-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilo', '0005_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
