# Generated by Django 4.0.4 on 2022-07-12 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilo', '0006_user_activation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activation_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
    ]
