# Generated by Django 4.0.4 on 2022-07-24 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_address', models.TextField(blank=True, null=True, verbose_name='Indirizzo di consegna')),
                ('shipping_delivery_time', models.TextField(blank=True, null=True, verbose_name='Orario di consegna')),
                ('shipping_required', models.BooleanField(default=False, verbose_name='Consegna a domicilio')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note ordine')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Pagato')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'ordine',
                'verbose_name_plural': 'ordini',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrizione stato')),
                ('badge_css_class', models.CharField(blank=True, max_length=255, null=True, verbose_name='Classe da applicare al badge')),
            ],
            options={
                'verbose_name': 'stato ordine',
                'verbose_name_plural': 'stati ordine',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=4, verbose_name='Prezzo unitario')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=4, verbose_name='Prezzo totale')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='vendite.order', verbose_name='Ordine')),
            ],
            options={
                'verbose_name': 'dettaglio ordine',
                'verbose_name_plural': 'dettagli ordini',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendite.orderstatus', verbose_name='Stato ordine'),
        ),
    ]
