# Generated by Django 4.0.4 on 2022-07-18 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payed',
            new_name='is_paid',
        ),
    ]
