# Generated by Django 4.0.4 on 2022-07-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendite', '0002_rename_payed_order_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='subtotal',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, verbose_name='Prezzo totale'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, verbose_name='Prezzo unitario'),
        ),
    ]
