# Generated by Django 4.0.4 on 2022-07-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendite', '0003_remove_order_subtotal_orderdetail_subtotal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='subtotal',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, verbose_name='Prezzo unitario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, verbose_name='Prezzo totale'),
        ),
    ]
