# Generated by Django 4.0.4 on 2022-07-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendite', '0004_remove_orderdetail_subtotal_orderdetail_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, verbose_name='Totale'),
            preserve_default=False,
        ),
    ]
