# Generated by Django 4.0.4 on 2022-07-18 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendite', '0005_order_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='subtotal',
        ),
    ]
