# Generated by Django 4.0.4 on 2022-07-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendite', '0006_remove_order_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='badge_css_class',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Classe da applicare al badget'),
        ),
    ]
