# Generated by Django 4.0.4 on 2022-07-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendite', '0007_orderstatus_badge_css_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='badge_css_class',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Classe da applicare al badge'),
        ),
    ]
